export enum OmletType {
    CONFIGURATION = 'configuration',
    CONFIGURATION_GENERAL = 'configuration_general',
    CONFIGURATION_CONNECTIVITY = 'configuration_connectivity',
    CONFIGURATION_DOOR = 'configuration_door',
    CONFIGURATION_LIGHT = 'configuration_light',
    CONFIGURATION_FEEDER = 'configuration_feeder',
    CONFIGURATION_FAN = 'configuration_fan',
    STATE = 'state',
    STATE_GENERAL = 'state_general',
    STATE_CONNECTIVITY = 'state_connectivity',
    STATE_DOOR = 'state_door',
    STATE_LIGHT = 'state_light',
    STATE_FEEDER = 'state_feeder',
    STATE_FAN = 'state_fan',
    DEVICE = 'device',
    ACTION = 'action',
    GROUP_USER = 'group_user',
    GROUP_SUBSET = 'group_subset',
    GROUP = 'group',
    NOTIFICATION_PERIOD = 'notification_period',
    NOTIFICATION_SETTINGS = 'notification_settings',
    USER = 'user',
}
